- hosts: dbserver
  become: true
  tasks: 

  - name: install mariadb package (CentOS)
    yum: 
      name: mariadb-server
      state: latest
    when: ansible_distribution == "CentOS"


  - name: "MariaDB - Restarting/Enabling"
    service: 
      name: mariadb
      state: restarted
      enabled: true

  - name: install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

