---
- hosts: workstations
  become: true
  roles:
    - base
    - workstations

- hosts: webservers
  become: true
  roles:
    - base
    - webservers

- hosts: fileservers
  become: true
  roles:
    - base
    - fileservers

- hosts: dbserver
  become: true
  roles: 
    - base
    - dbserver

