  - name: Install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install apache and php for CentOS servers
    tags: apache,centos,httpd
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Ensure /var/www/html exists
    tags: apache, webroot
    file:
      path: /var/www/html
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: Copy Default HTML file for Site
    tags: apache, apache2, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: start httpd (CentOS)
    tags: apache, centos,httpd
    service:
       name: httpd
       state: started
       enabled: true
    when: ansible_distribution == "CentOS"

  - name: Start Apache (Ubuntu)
    tags: apache, ubuntu, apache2
    service:
       name: apache2
       state: started
       enabled: true
    when: ansible_distribution == "Ubuntu"
